import { Connection, PublicKey } from "@solana/web3.js";
import { AnchorProvider, Program, Idl } from "@coral-xyz/anchor";
import { AnchorWallet } from "@solana/wallet-adapter-react";

// Program IDs from deployed contracts
export const LAUNCHPAD_PROGRAM_ID = new PublicKey(
    "GNc9f7vZtJVUbnYMFKx5JWbRWM9qT7TyZKkdt5BxhqJw"
);
export const SHIELD_PROGRAM_ID = new PublicKey(
    "5atx48YYJdXVuXFyEkW2kzHb7K3BhLDh7eab5cqovs9m"
);
export const VERIFIER_PROGRAM_ID = new PublicKey(
    "EL25TkoP8zcMcThDRn6ufsyN8HPjgxs6LPferAmoSURH"
);

// IDL imports - these will be generated by anchor build
// For now, we'll type them as Idl
import launchpadIdl from "../idl/launchpad.json";
import shieldIdl from "../idl/shield.json";

/**
 * Get an Anchor provider from wallet adapter
 */
export function getProvider(
    connection: Connection,
    wallet: AnchorWallet
): AnchorProvider {
    return new AnchorProvider(connection, wallet, {
        preflightCommitment: "confirmed",
    });
}

/**
 * Get the Launchpad program
 */
export function getLaunchpadProgram(provider: AnchorProvider): Program {
    return new Program(launchpadIdl as Idl, provider);
}

/**
 * Get the Shield program
 */
export function getShieldProgram(provider: AnchorProvider): Program {
    return new Program(shieldIdl as Idl, provider);
}

/**
 * Derive auction PDA
 */
export function deriveAuctionPDA(projectMint: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
        [Buffer.from("auction"), projectMint.toBuffer()],
        LAUNCHPAD_PROGRAM_ID
    );
}

/**
 * Derive user bid PDA
 */
export function deriveUserBidPDA(
    auction: PublicKey,
    nullifier: Uint8Array
): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
        [Buffer.from("bid"), auction.toBuffer(), Buffer.from(nullifier)],
        LAUNCHPAD_PROGRAM_ID
    );
}

/**
 * Derive vault state PDA for Shield
 */
export function deriveVaultStatePDA(jitoMint: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
        [Buffer.from("vault_state"), jitoMint.toBuffer()],
        SHIELD_PROGRAM_ID
    );
}

/**
 * Derive Payment Vault PDA
 */
export function derivePaymentVaultPDA(auction: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
        [Buffer.from("payment_vault"), auction.toBuffer()],
        LAUNCHPAD_PROGRAM_ID
    );
}

/**
 * Derive Project Vault PDA
 */
export function deriveProjectVaultPDA(auction: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
        [Buffer.from("project_vault"), auction.toBuffer()],
        LAUNCHPAD_PROGRAM_ID
    );
}
